#!/bin/bash

cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob aq
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hf
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob mas
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob wuhu
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob bj
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob fz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob quanzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xm
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zhangzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dg
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob fs
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob gz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hui
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jiangmen
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob qy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zh
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zhanjiang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zs
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob gy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob bh
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob fcg
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob gl
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob liuzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nn
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob lz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ez
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob huangshi
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob wh
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yichang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob cs
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob changde
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zhuzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob bd
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob lf
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sjz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ts
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zjk
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hk
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob san
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob kf
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob luoyang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xinxiang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xc
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zk
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hrb
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob changzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob haimen
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ha
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ks
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nj
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nt
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob su
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob wx
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yc
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zj
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob cc
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jl
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ganzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jiujiang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jian
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nc
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sr
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dl
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dd
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob baotou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hhht
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yinchuan
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sh
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob cd
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dy
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dazhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob liangshan
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob mianyang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nanchong
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob heze
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jn
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jining
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob linyi
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob qd
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ta
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob wf
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob weihai
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yt
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob zb
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob baoji
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hanzhong
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xa
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob xianyang
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob ty
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob tj
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob dali
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob km
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob hz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob huzhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jx
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob jh
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob nb
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob sx
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob taizhou
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob wz
cd /home/shihongda/website/PySpider/ljSpider && python3 ./run.py initListJob yw